[package]
name = "atomic-swap"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "atomic_swap"

[dependencies]
solana-program = "1.18.0"
spl-token = "4.0.0"
borsh = "0.10.3"
thiserror = "1.0.50"
